import 'package:sakaynow_buenatoda/models/ride.dart';
import 'package:sakaynow_buenatoda/models/ride_location.dart';
import 'package:sakaynow_buenatoda/models/ride_status.dart';

Ride buildRideFixture({
  String bookingId = 'booking-1',
  RideStatus status = RideStatus.searching,
  int? estimatedDistanceMeters = 3600,
  int? estimatedDurationSeconds = 900,
  int? driverToPickupDistanceMeters = 1200,
  int? driverToPickupDurationSeconds = 300,
  int? remainingRideDistanceMeters = 2400,
  int? remainingRideDurationSeconds = 480,
  int? grossFare,
  double? commissionRate,
  int? commissionAmount,
  int? driverNetEarnings,
  String? driverPayoutStatus,
  String paymentMethod = 'cash',
  String paymentProvider = 'cash',
  String paymentStatus = 'cash_pending',
  DateTime? createdAt,
  DateTime? updatedAt,
  DateTime? completedAt,
  DateTime? cancelledAt,
  int fareAmount = 50,
}) {
  return Ride(
    bookingId: bookingId,
    passengerId: 'passenger-1',
    driverId: 'driver-1',
    preferredDriverId: null,
    declinedDriverIds: const <String>[],
    status: status,
    pickupLocation: const RideLocation(
      address: 'Buenavista Plaza',
      latitude: 10.7000,
      longitude: 122.6260,
    ),
    dropoffLocation: const RideLocation(
      address: 'New Poblacion',
      latitude: 10.6800,
      longitude: 122.6400,
    ),
    route: null,
    driverLocation: null,
    estimatedDistanceMeters: estimatedDistanceMeters,
    estimatedDurationSeconds: estimatedDurationSeconds,
    driverToPickupDistanceMeters: driverToPickupDistanceMeters,
    driverToPickupDurationSeconds: driverToPickupDurationSeconds,
    remainingRideDistanceMeters: remainingRideDistanceMeters,
    remainingRideDurationSeconds: remainingRideDurationSeconds,
    createdAt: createdAt,
    updatedAt: updatedAt,
    completedAt: completedAt,
    cancelledBy: null,
    cancelledAt: cancelledAt,
    fareLabel: 'PHP 50',
    fareAmount: fareAmount,
    fareRuleLabel: null,
    grossFare: grossFare,
    commissionRate: commissionRate,
    commissionAmount: commissionAmount,
    driverNetEarnings: driverNetEarnings,
    driverPayoutStatus: driverPayoutStatus,
    paymentMethod: paymentMethod,
    paymentMethodLabel: 'Cash',
    paymentMethodId: 'cash',
    paymentMethodType: 'cash',
    paymentProvider: paymentProvider,
    paymentStatus: paymentStatus,
    xenditInvoiceId: null,
    checkoutUrl: null,
    driverPassengerReviewRating: null,
    passengerDriverReviewRating: null,
    passengerDriverReviewComment: null,
  );
}
