// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLua-BrMvRidWmPkbCXgoJ2HpIPB26GmY',
    appId: '1:307925311207:web:25086075ec7d6e35170c42',
    messagingSenderId: '307925311207',
    projectId: 'sakaynow-buenatoda',
    authDomain: 'sakaynow-buenatoda.firebaseapp.com',
    storageBucket: 'sakaynow-buenatoda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARiAK_6ZAJT2f06Si3oTxm5I-wSYSKWro',
    appId: '1:307925311207:android:03bb2e1731bc2046170c42',
    messagingSenderId: '307925311207',
    projectId: 'sakaynow-buenatoda',
    storageBucket: 'sakaynow-buenatoda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCciR9EOyJHMr0qrX61ONmGnz95yua0sI',
    appId: '1:307925311207:ios:f25e32c3ebcd6fd0170c42',
    messagingSenderId: '307925311207',
    projectId: 'sakaynow-buenatoda',
    storageBucket: 'sakaynow-buenatoda.firebasestorage.app',
    iosBundleId: 'com.example.sakaynowBuenatoda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCciR9EOyJHMr0qrX61ONmGnz95yua0sI',
    appId: '1:307925311207:ios:f25e32c3ebcd6fd0170c42',
    messagingSenderId: '307925311207',
    projectId: 'sakaynow-buenatoda',
    storageBucket: 'sakaynow-buenatoda.firebasestorage.app',
    iosBundleId: 'com.example.sakaynowBuenatoda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLua-BrMvRidWmPkbCXgoJ2HpIPB26GmY',
    appId: '1:307925311207:web:d1eab4ba2da2f5fb170c42',
    messagingSenderId: '307925311207',
    projectId: 'sakaynow-buenatoda',
    authDomain: 'sakaynow-buenatoda.firebaseapp.com',
    storageBucket: 'sakaynow-buenatoda.firebasestorage.app',
  );
}
